GearAdd = (vehicle player);
GearAdd addWeapon 'arifle_Katiba_GL_F';
GearAdd addMagazine '30Rnd_65x39_caseless_green';
GearAdd addMagazine '30Rnd_65x39_caseless_green';
GearAdd addMagazine '30Rnd_65x39_caseless_green';
GearAdd addMagazine '30Rnd_65x39_caseless_green';
GearAdd addMagazine '30Rnd_65x39_caseless_green';
GearAdd addMagazine '30Rnd_65x39_caseless_green';
GearAdd addMagazine '30Rnd_65x39_caseless_green';
GearAdd addMagazine '30Rnd_65x39_caseless_green';
GearAdd addMagazine '1Rnd_HE_Grenade_shell';
GearAdd addMagazine '1Rnd_HE_Grenade_shell';
GearAdd addMagazine '1Rnd_HE_Grenade_shell';
GearAdd addMagazine '1Rnd_HE_Grenade_shell';
GearAdd addMagazine '1Rnd_HE_Grenade_shell';
GearAdd addMagazine '1Rnd_Smoke_Grenade_shell';
GearAdd addMagazine '1Rnd_Smoke_Grenade_shell';
GearAdd addMagazine '1Rnd_Smoke_Grenade_shell';