GearAdd = (vehicle player);
GearAdd addWeapon 'srifle_LRR_F';
GearAdd addMagazine '7Rnd_408_Mag';
GearAdd addMagazine '7Rnd_408_Mag';
GearAdd addMagazine '7Rnd_408_Mag';
GearAdd addMagazine '7Rnd_408_Mag';
GearAdd addMagazine '7Rnd_408_Mag';
GearAdd addMagazine '7Rnd_408_Mag';
GearAdd addMagazine '7Rnd_408_Mag';
GearAdd addMagazine '7Rnd_408_Mag';
GearAdd addMagazine '7Rnd_408_Mag';
