removeAllActions player;
ScriptCCorrection = "admintools\event\Filtres\CCorrectionON.sqf";
ScriptCCorrectionNull = "admintools\event\Filtres\Null.sqf";
ActionContruction00 = player addaction ["<t color='#55FF55'>Fermer le menu</t>",ScriptCCorrectionNull];
ActionCC01 = player addaction ["Clear contrast",ScriptCCorrection,["1.sqf"]];
ActionCC02 = player addaction ["Wasteland",ScriptCCorrection,["2.sqf"]];
ActionCC03 = player addaction ["Dark draining",ScriptCCorrection,["3.sqf"]];
ActionCC04 = player addaction ["Sandy",ScriptCCorrection,["4.sqf"]];
ActionCC05 = player addaction ["Sumer Chernarus",ScriptCCorrection,["5.sqf"]];
ActionCC06 = player addaction ["Dog Vision",ScriptCCorrection,["6.sqf"]];
ActionCC07 = player addaction ["Tropical",ScriptCCorrection,["7.sqf"]];
ActionCC08 = player addaction ["Photo (bug)",ScriptCCorrection,["8.sqf"]];
ActionCC09 = player addaction ["WarZone (bug)",ScriptCCorrection,["9.sqf"]];
ActionCC10 = player addaction ["Operation Flashpoint",ScriptCCorrection,["10.sqf"]];
ActionCC11 = player addaction ["Africa",ScriptCCorrection,["11.sqf"]];
ActionCC12 = player addaction ["Blue",ScriptCCorrection,["12.sqf"]];
ActionCC13 = player addaction ["Arma mission colours",ScriptCCorrection,["13.sqf"]];
ActionCC14 = player addaction ["Heavy Colour Correction",ScriptCCorrection,["14.sqf"]];
ActionCC15 = player addaction ["Zombie View",ScriptCCorrection,["15.sqf"]];